name: "Roblox Game"
description: "Report an issue with the Roblox Game."
title: "[Bug]: "
assignees: "plainenglishh,EletricalFuse"
labels: "bug,needs-triage"
body:
- type: textarea
  id: description
  attributes:
    label: Describe the bug
    description: "Please be clear and concise."
  validations:
    required: true
- type: input
  id: prevalence
  attributes:
    label: Frequency
    description: "How often do you see this bug?"
    placeholder: "Every time I join"
  validations:
    required: true
- type: input
  id: contact
  attributes:
    label: Contact
    description: "How can we contact you if we need more details?"
    placeholder: "Discord: Example#0000"
  validations:
    required: true
- type: dropdown
  id: location
  attributes:
    label: "Where did this occur?"
    options:
      - Stable Server (Normal)
      - Test Server
      - Development Server
      - Launcher
  validations:
    required: true
