name: "Test Performance Report"
description: "Report your performance stats from a test session."
title: "[Performance]: "
assignees: "plainenglishh,EletricalFuse"
labels: "Performance Report"
body:
- type: textarea
  id: description
  attributes:
    label: Attach a screenshot of the debug stats and describe your computers specs here.
    description: "You can find the debug stats in the lower right corner of your screen"
  validations:
    required: true
- type: dropdown
  id: location
  attributes:
    label: "Did you experience poor performance in game?"
    options:
      - "Yes"
      - "No clue"
      - "No"
  validations:
    required: true
